SELECT
	AREA_NAME 지역명,
	MEMBER_ID 아이디,
	MEMBER_NAME 이름,
	GRADE_NAME 등급명
FROM TB_MEMBER M
JOIN TB_GRADE ON (GRADE = GRADE_CODE)
JOIN TB_AREA A ON (M.AREA_CODE = A.AREA_CODE)
WHERE
	M.AREA_CODE = (
	SELECT AREA_CODE
	FROM TB_MEMBER
	WHERE MEMBER_NAME = '김영희')
ORDER BY 이름 ASC;


SELECT
	AREA_NAME 지역명,
	MEMBER_ID 아이디,
	MEMBER_NAME 이름,
	GRADE_NAME 등급명
FROM TB_MEMBER 
JOIN TB_GRADE ON (GRADE = GRADE_CODE)
JOIN TB_AREA  USING (AREA_CODE)
WHERE
	AREA_CODE = (
	SELECT AREA_CODE
	FROM TB_MEMBER
	WHERE MEMBER_NAME = '김영희')
ORDER BY 이름 ASC;